# Generated by Django 3.0.3 on 2020-09-13 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('location', models.CharField(default="", max_length=32), ),
                ('logo', models.URLField(default="https://place-hold.it/100x60")),
                ('description', models.CharField(default="", max_length=128)),
                ('employee_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=32)),
                ('picture', models.URLField(default="https://place-hold.it/100x60")),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('skills', models.CharField(max_length=128)),
                ('description', models.CharField(default="", max_length=128)),
                ('salary_min', models.IntegerField()),
                ('salary_max', models.IntegerField()),
                ('published_at', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies',
                                              to='app_catalog.Company')),
                ('specialty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                related_name='vacancies', to='app_catalog.Specialty')),
            ],
        ),
    ]
