# Generated by Django 3.0.3 on 2020-09-27 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('app_catalog', '0001_initial'), ('app_catalog', '0002_auto_20200917_2301'), ('app_catalog', '0003_auto_20200919_1325'), ('app_catalog', '0004_auto_20200919_1453'), ('app_catalog', '0005_application'), ('app_catalog', '0006_auto_20200921_1623'), ('app_catalog', '0007_auto_20200921_1747'), ('app_catalog', '0008_auto_20200927_2121')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('location', models.CharField(max_length=32)),
                ('logo', models.ImageField(null=True, upload_to='company_images')),
                ('description', models.TextField()),
                ('employee_count', models.CharField(max_length=20)),
                ('owner', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('title', models.CharField(choices=[('Фронтенд', 'Frontend'), ('Бэкенд', 'Backend'), ('Геймдев', 'Gamedev'), ('Девопс', 'Devops'), ('Дизайн', 'Design'), ('Продукты', 'Products'), ('Менеджмент', 'Management'), ('Тестирование', 'Testing')], max_length=32)),
                ('picture', models.ImageField(null=True, upload_to='speciality_images')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('skills', models.TextField()),
                ('description', models.TextField()),
                ('salary_min', models.IntegerField()),
                ('salary_max', models.IntegerField()),
                ('published_at', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='app_catalog.Company')),
                ('specialty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancies', to='app_catalog.Specialty')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('written_username', models.CharField(max_length=128)),
                ('written_phone', models.CharField(max_length=16)),
                ('written_cover_letter', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='app_catalog.Vacancy')),
            ],
        ),
    ]
