# Generated by Django 3.0.3 on 2020-10-02 21:02

import app_catalog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_catalog', '0001_squashed_0008_auto_20200927_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(null=True, upload_to=app_catalog.models.company_logo_path),
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Не ищу', 'Not Active'), ('Рассматриваю', 'Checking'), ('Ищу работу', 'Active')], max_length=20)),
                ('salary', models.IntegerField()),
                ('grade', models.CharField(choices=[('Стажер', 'Intern'), ('Джуниор', 'Junior'), ('Миддл', 'Middle'), ('Синьор', 'Senior'), ('Лид', 'Lead')], max_length=30)),
                ('education', models.TextField()),
                ('experience', models.TextField()),
                ('specialty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resumes', to='app_catalog.Specialty')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
