# Generated by Django 3.0.3 on 2020-09-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0006_auto_20200921_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialty',
            name='title',
            field=models.CharField(choices=[('Фронтенд', 'Frontend'), ('Бэкенд', 'Backend'), ('Геймдев', 'Gamedev'), ('Девопс', 'Devops'), ('Дизайн', 'Design'), ('Продукты', 'Products'), ('Менеджмент', 'Management'), ('Тестирование', 'Testing')], max_length=32),
        ),
    ]
